/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void wBtn_click(GButton source, GEvent event) { //_CODE_:wBtn:471796:
  println("wBtn - GButton >> GEvent." + event + " @ " + millis());
  port.write("W");
} //_CODE_:wBtn:471796:

public void aBtn_click(GButton source, GEvent event) { //_CODE_:aBtn:529102:
  println("aBtn - GButton >> GEvent." + event + " @ " + millis());
  port.write("A");
} //_CODE_:aBtn:529102:

public void sBtn_click(GButton source, GEvent event) { //_CODE_:sBtn:487489:
  println("sBtn - GButton >> GEvent." + event + " @ " + millis());
  port.write("S");
} //_CODE_:sBtn:487489:

public void dBtn_click(GButton source, GEvent event) { //_CODE_:dBtn:325743:
  println("dBtn - GButton >> GEvent." + event + " @ " + millis());
  port.write("D");
} //_CODE_:dBtn:325743:

public void responseTxt_change(GTextArea source, GEvent event) { //_CODE_:responseTextArea:801252:
  println("responseTextArea - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:responseTextArea:801252:

public void completeBtn_click(GButton source, GEvent event) { //_CODE_:completeBtn:917622:
  println("completeBtn - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:completeBtn:917622:

public void roomBtn_click(GButton source, GEvent event) { //_CODE_:roomBtn:562327:
  println("roomBtn - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:roomBtn:562327:

public void corridorBtn_click(GButton source, GEvent event) { //_CODE_:corridorBtn:589553:
  println("corridorBtn - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:corridorBtn:589553:

public void endBtn_click(GButton source, GEvent event) { //_CODE_:endBtn:377588:
  println("endBtn - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:endBtn:377588:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  wBtn = new GButton(this, 80, 15, 61, 51);
  wBtn.setText("W");
  wBtn.setTextBold();
  wBtn.addEventHandler(this, "wBtn_click");
  aBtn = new GButton(this, 12, 73, 62, 51);
  aBtn.setText("A");
  aBtn.setTextBold();
  aBtn.addEventHandler(this, "aBtn_click");
  sBtn = new GButton(this, 81, 72, 62, 53);
  sBtn.setText("S");
  sBtn.setTextBold();
  sBtn.addEventHandler(this, "sBtn_click");
  dBtn = new GButton(this, 150, 71, 64, 54);
  dBtn.setText("D");
  dBtn.setTextBold();
  dBtn.addEventHandler(this, "dBtn_click");
  responseTextArea = new GTextArea(this, 145, 236, 328, 80, G4P.SCROLLBARS_NONE);
  responseTextArea.setText("Hi from Zumo");
  responseTextArea.setOpaque(true);
  responseTextArea.addEventHandler(this, "responseTxt_change");
  textAreaLbl = new GLabel(this, 262, 198, 124, 47);
  textAreaLbl.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  textAreaLbl.setText("Message from Zumo");
  textAreaLbl.setOpaque(false);
  completeBtn = new GButton(this, 334, 27, 75, 43);
  completeBtn.setText("Complete");
  completeBtn.setTextBold();
  completeBtn.addEventHandler(this, "completeBtn_click");
  roomBtn = new GButton(this, 277, 84, 80, 30);
  roomBtn.setText("Room");
  roomBtn.setTextBold();
  roomBtn.addEventHandler(this, "roomBtn_click");
  corridorBtn = new GButton(this, 374, 84, 80, 30);
  corridorBtn.setText("Corridor");
  corridorBtn.setTextBold();
  corridorBtn.addEventHandler(this, "corridorBtn_click");
  endBtn = new GButton(this, 13, 285, 102, 30);
  endBtn.setText("End ofTrack");
  endBtn.setTextBold();
  endBtn.addEventHandler(this, "endBtn_click");
}

// Variable declarations 
// autogenerated do not edit
GButton wBtn; 
GButton aBtn; 
GButton sBtn; 
GButton dBtn; 
GTextArea responseTextArea; 
GLabel textAreaLbl; 
GButton completeBtn; 
GButton roomBtn; 
GButton corridorBtn; 
GButton endBtn; 